version: '3.2'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1.13.11-alpine
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
      - log:/var/log/nginx

  php:
    build:
      context: ./docker/php
    depends_on:
      - database
    working_dir: /srv
    volumes:
      - ./:/srv/

  node:
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

  phpmyadmin:
      container_name: container_phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
          - "8080:80"
      links:
        - database:db

volumes:
  database: ~
  log: ~
